/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Vini
 */
public class AtestadoView extends javax.swing.JFrame {

    /** Creates new form AtestadoView */
    public AtestadoView() {
        setTitle("Atestado do Paciente | Saúde & Cia");
        setIcon();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txthrIniAtes = new javax.swing.JTextField();
        txtAs = new javax.swing.JTextField();
        txtHrFimAtest = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNomeMed = new javax.swing.JTextField();
        txtCrm = new javax.swing.JTextField();
        lblCpfMed = new javax.swing.JLabel();
        txtCpfMed = new javax.swing.JTextField();
        lblDtAtend = new javax.swing.JLabel();
        txtDtAtendimento = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("##/##/####");
            txtDtAtendimento = new javax.swing.JFormattedTextField(cpf);
        } catch (Exception e) {
            System.out.println(e.getMessage());    
        }
        separador = new javax.swing.JSeparator();
        lblHoraIni = new javax.swing.JLabel();
        lblCpfPac = new javax.swing.JLabel();
        txtHrIni = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("##:##");
            txtHrIni = new javax.swing.JFormattedTextField(cpf);
        } catch (Exception e) {
            System.out.println(e.getMessage());    
        }
        txtCpfPac = new javax.swing.JTextField();
        lblHrFim = new javax.swing.JLabel();
        txtHrFim = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("##:##");
            txtHrFim = new javax.swing.JFormattedTextField(cpf);
        } catch (Exception e) {
            System.out.println(e.getMessage());    
        }
        btnGerar = new javax.swing.JButton();
        txtDeclaro = new javax.swing.JTextField();
        txtNomePac = new javax.swing.JTextField();
        txtEsteve = new javax.swing.JTextField();
        txtDtAtendAtestado = new javax.swing.JTextField();
        txtDas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txthrIniAtes.setEditable(false);
        txthrIniAtes.setBorder(null);

        txtAs.setEditable(false);
        txtAs.setText(" às");
        txtAs.setBorder(null);

        txtHrFimAtest.setEditable(false);
        txtHrFimAtest.setBorder(null);

        txtNomeMed.setEditable(false);
        txtNomeMed.setBorder(null);

        txtCrm.setEditable(false);
        txtCrm.setBorder(null);

        lblCpfMed.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCpfMed.setText("CPF do Médico");

        lblDtAtend.setText("Data do Atend.");

        lblHoraIni.setText("Hora Inicial");

        lblCpfPac.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCpfPac.setText("CPF do Paciente");

        lblHrFim.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHrFim.setText("Hora Final");

        btnGerar.setBackground(new java.awt.Color(0, 0, 0));
        btnGerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGerar.setText("Gerar");

        txtDeclaro.setEditable(false);
        txtDeclaro.setText("Declaro para os devidos fins, que o Sr(ª).");
        txtDeclaro.setBorder(null);

        txtNomePac.setEditable(false);
        txtNomePac.setBorder(null);

        txtEsteve.setEditable(false);
        txtEsteve.setText("esteve nesta unidade hospitalar/clínica no dia ");
        txtEsteve.setBorder(null);

        txtDtAtendAtestado.setEditable(false);
        txtDtAtendAtestado.setBorder(null);

        txtDas.setEditable(false);
        txtDas.setText(" das");
        txtDas.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDeclaro, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomePac))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEsteve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDtAtendAtestado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txthrIniAtes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHrFimAtest, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(txtNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCpfPac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpfPac, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCpfMed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpfMed))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDtAtend)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDtAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHoraIni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHrIni, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHrFim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHrFim, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGerar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfPac)
                    .addComponent(txtCpfPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfMed)
                    .addComponent(txtCpfMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtAtend)
                    .addComponent(txtDtAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoraIni)
                    .addComponent(txtHrIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHrFim)
                    .addComponent(txtHrFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDeclaro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEsteve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDtAtendAtestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txthrIniAtes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHrFimAtest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtestadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtestadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtestadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtestadoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtestadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCpfMed;
    private javax.swing.JLabel lblCpfPac;
    private javax.swing.JLabel lblDtAtend;
    private javax.swing.JLabel lblHoraIni;
    private javax.swing.JLabel lblHrFim;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField txtAs;
    private javax.swing.JTextField txtCpfMed;
    private javax.swing.JTextField txtCpfPac;
    private javax.swing.JTextField txtCrm;
    private javax.swing.JTextField txtDas;
    private javax.swing.JTextField txtDeclaro;
    private javax.swing.JTextField txtDtAtendAtestado;
    private javax.swing.JTextField txtDtAtendimento;
    private javax.swing.JTextField txtEsteve;
    private javax.swing.JTextField txtHrFim;
    private javax.swing.JTextField txtHrFimAtest;
    private javax.swing.JTextField txtHrIni;
    private javax.swing.JTextField txtNomeMed;
    private javax.swing.JTextField txtNomePac;
    private javax.swing.JTextField txthrIniAtes;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("icone.png"))));
    }

    public JButton getBtnGerar() {
        return btnGerar;
    }

    public void setBtnGerar(JButton btnGerar) {
        this.btnGerar = btnGerar;
    }

    public JTextField getTxtCpfMed() {
        return txtCpfMed;
    }

    public void setTxtCpfMed(JTextField txtCpfMed) {
        this.txtCpfMed = txtCpfMed;
    }

    public JTextField getTxtCpfPac() {
        return txtCpfPac;
    }

    public void setTxtCpfPac(JTextField txtCpfPac) {
        this.txtCpfPac = txtCpfPac;
    }

    public JTextField getTxtCrm() {
        return txtCrm;
    }

    public void setTxtCrm(JTextField txtCrm) {
        this.txtCrm = txtCrm;
    }

    public JTextField getTxtDtAtendAtestado() {
        return txtDtAtendAtestado;
    }

    public void setTxtDtAtendAtestado(JTextField txtDtAtendAtestado) {
        this.txtDtAtendAtestado = txtDtAtendAtestado;
    }

    public JTextField getTxtDtAtendimento() {
        return txtDtAtendimento;
    }

    public void setTxtDtAtendimento(JTextField txtDtAtendimento) {
        this.txtDtAtendimento = txtDtAtendimento;
    }

    public JTextField getTxtHrFim() {
        return txtHrFim;
    }

    public void setTxtHrFim(JTextField txtHrFim) {
        this.txtHrFim = txtHrFim;
    }

    public JTextField getTxtHrFimAtest() {
        return txtHrFimAtest;
    }

    public void setTxtHrFimAtest(JTextField txtHrFimAtest) {
        this.txtHrFimAtest = txtHrFimAtest;
    }

    public JTextField getTxtHrIni() {
        return txtHrIni;
    }

    public void setTxtHrIni(JTextField txtHrIni) {
        this.txtHrIni = txtHrIni;
    }

    public JTextField getTxtNomeMed() {
        return txtNomeMed;
    }

    public void setTxtNomeMed(JTextField txtNomeMed) {
        this.txtNomeMed = txtNomeMed;
    }

    public JTextField getTxtNomePac() {
        return txtNomePac;
    }

    public void setTxtNomePac(JTextField txtNomePac) {
        this.txtNomePac = txtNomePac;
    }

    public JTextField getTxthrIniAtes() {
        return txthrIniAtes;
    }

    public void setTxthrIniAtes(JTextField txthrIniAtes) {
        this.txthrIniAtes = txthrIniAtes;
    }

    
}
