/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Luiz Flávio
 */
public class CadConsultaView extends javax.swing.JFrame {

    /**
     * Creates new form CadConsultaView
     */
    public CadConsultaView() {
        setTitle("Cadastrar Consulta | Saúde & Cia");
        setIcon();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRadGroup = new javax.swing.ButtonGroup();
        lblCpfPac = new javax.swing.JLabel();
        txtCpfPac = new javax.swing.JTextField();
        lblCpfMed = new javax.swing.JLabel();
        txtCpfMed = new javax.swing.JTextField();
        lblDtHora = new javax.swing.JLabel();
        txtDtHora = new javax.swing.JTextField();
        try {
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("##/##/#### ##:##");
            txtDtHora = new javax.swing.JFormattedTextField(cpf);
        } catch (Exception e) {
            System.out.println(e.getMessage());    
        }
        btnRadNormal = new javax.swing.JRadioButton();
        lblTpCons = new javax.swing.JLabel();
        btnRadRetorno = new javax.swing.JRadioButton();
        btnCadastrar = new javax.swing.JButton();
        lblNomePac = new javax.swing.JLabel();
        lblDtNascPac = new javax.swing.JLabel();
        txtNomePac = new javax.swing.JTextField();
        txtDtNascPac = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        lblNomeMed = new javax.swing.JLabel();
        lblCrm = new javax.swing.JLabel();
        txtNomeMed = new javax.swing.JTextField();
        txtCrm = new javax.swing.JTextField();
        lblDtNascMed = new javax.swing.JLabel();
        txtDtNascMed = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCpfPac.setText("CPF do Paciente");

        lblCpfMed.setText("CPF do Médico");

        lblDtHora.setText("Data e Hora");

        btnRadGroup.add(btnRadNormal);
        btnRadNormal.setText("Normal");

        lblTpCons.setText("Tipo da Consulta");

        btnRadGroup.add(btnRadRetorno);
        btnRadRetorno.setText("Retorno");

        btnCadastrar.setBackground(new java.awt.Color(0, 153, 255));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");

        lblNomePac.setText("Nome");

        lblDtNascPac.setText("Data Nasc.");

        txtNomePac.setEditable(false);
        txtNomePac.setBorder(null);

        txtDtNascPac.setEditable(false);
        txtDtNascPac.setBorder(null);

        lblNomeMed.setText("Nome");

        lblCrm.setText("CRM");

        txtNomeMed.setEditable(false);
        txtNomeMed.setBorder(null);

        txtCrm.setEditable(false);
        txtCrm.setBorder(null);

        lblDtNascMed.setText("Data de Nasc.");

        txtDtNascMed.setEditable(false);
        txtDtNascMed.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCpfMed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCpfMed, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRadNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRadRetorno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDtHora)
                                .addComponent(lblTpCons)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCpfPac)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCpfPac, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDtNascPac)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDtNascPac))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNomePac)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNomePac))
                                .addComponent(separador1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDtNascMed)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtDtNascMed)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblCrm)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblNomeMed)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtNomeMed)))
                                    .addGap(1, 1, 1)))
                            .addComponent(txtDtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfPac)
                    .addComponent(txtCpfPac, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomePac)
                    .addComponent(txtNomePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtNascPac)
                    .addComponent(txtDtNascPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfMed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeMed)
                    .addComponent(txtNomeMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCrm)
                    .addComponent(txtCrm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtNascMed)
                    .addComponent(txtDtNascMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lblDtHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTpCons)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRadNormal)
                    .addComponent(btnRadRetorno)
                    .addComponent(btnCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadConsultaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadConsultaView().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("icone.png"))));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup btnRadGroup;
    private javax.swing.JRadioButton btnRadNormal;
    private javax.swing.JRadioButton btnRadRetorno;
    private javax.swing.JLabel lblCpfMed;
    private javax.swing.JLabel lblCpfPac;
    private javax.swing.JLabel lblCrm;
    private javax.swing.JLabel lblDtHora;
    private javax.swing.JLabel lblDtNascMed;
    private javax.swing.JLabel lblDtNascPac;
    private javax.swing.JLabel lblNomeMed;
    private javax.swing.JLabel lblNomePac;
    private javax.swing.JLabel lblTpCons;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JTextField txtCpfMed;
    private javax.swing.JTextField txtCpfPac;
    private javax.swing.JTextField txtCrm;
    private javax.swing.JTextField txtDtHora;
    private javax.swing.JTextField txtDtNascMed;
    private javax.swing.JTextField txtDtNascPac;
    private javax.swing.JTextField txtNomeMed;
    private javax.swing.JTextField txtNomePac;
    // End of variables declaration//GEN-END:variables

    public JRadioButton getBtnRadNormal() {
        return btnRadNormal;
    }

    public void setBtnRadNormal(JRadioButton btnRadNormal) {
        this.btnRadNormal = btnRadNormal;
    }

    public JRadioButton getBtnRadRetorno() {
        return btnRadRetorno;
    }

    public void setBtnRadRetorno(JRadioButton btnRadRetorno) {
        this.btnRadRetorno = btnRadRetorno;
    }

    public JTextField getTxtCpfMed() {
        return txtCpfMed;
    }

    public void setTxtCpfMed(JTextField txtCpfMed) {
        this.txtCpfMed = txtCpfMed;
    }

    public JTextField getTxtCpfPac() {
        return txtCpfPac;
    }

    public void setTxtCpfPac(JTextField txtCpfPac) {
        this.txtCpfPac = txtCpfPac;
    }

    public JTextField getTxtDtHora() {
        return txtDtHora;
    }

    public void setTxtDtHora(JTextField txtDtHora) {
        this.txtDtHora = txtDtHora;
    }

    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public ButtonGroup getBtnRadGroup() {
        return btnRadGroup;
    }

    public void setBtnRadGroup(ButtonGroup btnRadGroup) {
        this.btnRadGroup = btnRadGroup;
    }

    public JTextField getTxtCrm() {
        return txtCrm;
    }

    public void setTxtCrm(JTextField txtCrm) {
        this.txtCrm = txtCrm;
    }

    public JTextField getTxtDtNascMed() {
        return txtDtNascMed;
    }

    public void setTxtDtNascMed(JTextField txtDtNascMed) {
        this.txtDtNascMed = txtDtNascMed;
    }

    public JTextField getTxtDtNascPac() {
        return txtDtNascPac;
    }

    public void setTxtDtNascPac(JTextField txtDtNascPac) {
        this.txtDtNascPac = txtDtNascPac;
    }

    public JTextField getTxtNomeMed() {
        return txtNomeMed;
    }

    public void setTxtNomeMed(JTextField txtNomeMed) {
        this.txtNomeMed = txtNomeMed;
    }

    public JTextField getTxtNomePac() {
        return txtNomePac;
    }

    public void setTxtNomePac(JTextField txtNomePac) {
        this.txtNomePac = txtNomePac;
    }
}
