/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Vini
 */
public class CadDadosAdcView extends javax.swing.JFrame {

    /**
     * Creates new form CadDadosAdcView
     */
    public CadDadosAdcView() {
        setTitle("Cadastrar Dados Adicionais do Paciente | Saúde & Cia");
        setIcon();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRadGroupFuma = new javax.swing.ButtonGroup();
        btnRadGroupBebe = new javax.swing.ButtonGroup();
        btnRadGroupColesterol = new javax.swing.ButtonGroup();
        btnRadGroupDiabetes = new javax.swing.ButtonGroup();
        btnRadGroupAlergias = new javax.swing.ButtonGroup();
        btnRadGroupProbCardiaco = new javax.swing.ButtonGroup();
        btnRadGroupCirurgia = new javax.swing.ButtonGroup();
        separador = new javax.swing.JSeparator();
        lblEmail = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblDtNasc = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtDtNasc = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lblConvenio = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        txtConvenio = new javax.swing.JTextField();
        txtRg = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        lblCpfConsulta = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtCpfConsulta = new javax.swing.JTextField();
        lblCelular = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        txtCelular = new javax.swing.JTextField();
        separadorVertical = new javax.swing.JSeparator();
        lblFuma = new javax.swing.JLabel();
        btnRadFumaSim = new javax.swing.JRadioButton();
        btnRadFumaNao = new javax.swing.JRadioButton();
        lblBebe = new javax.swing.JLabel();
        btnRadBebeSim = new javax.swing.JRadioButton();
        btnRadBebeNao = new javax.swing.JRadioButton();
        lblColesterol = new javax.swing.JLabel();
        btnRadColesterolSim = new javax.swing.JRadioButton();
        btnRadColesterolNao = new javax.swing.JRadioButton();
        lblDiabetes = new javax.swing.JLabel();
        btnRadDiabetesSim = new javax.swing.JRadioButton();
        btnRadDiabetesNao = new javax.swing.JRadioButton();
        lblAlergias = new javax.swing.JLabel();
        btnRadAlergiaSim = new javax.swing.JRadioButton();
        btnRadAlergiaNao = new javax.swing.JRadioButton();
        lblProbCardiacos = new javax.swing.JLabel();
        btnRadProbCardiacoSim = new javax.swing.JRadioButton();
        btnRadProbCardiacoNao = new javax.swing.JRadioButton();
        lblCirurgias = new javax.swing.JLabel();
        btnRadCirurgiaSim = new javax.swing.JRadioButton();
        btnRadCirurgiaNao = new javax.swing.JRadioButton();
        separador1 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        separador3 = new javax.swing.JSeparator();
        separador4 = new javax.swing.JSeparator();
        separador5 = new javax.swing.JSeparator();
        separador6 = new javax.swing.JSeparator();
        separador7 = new javax.swing.JSeparator();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblEmail.setText("E-mail");

        lblNome.setText("Nome");

        txtEmail.setEditable(false);
        txtEmail.setBorder(null);

        txtNome.setEditable(false);
        txtNome.setBorder(null);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblDtNasc.setText("Data de Nascimento");

        lblCpf.setText("CPF");

        txtDtNasc.setEditable(false);
        txtDtNasc.setBorder(null);

        txtCpf.setEditable(false);
        txtCpf.setBorder(null);

        lblConvenio.setText("Convênio");

        lblRg.setText("RG");

        txtConvenio.setEditable(false);
        txtConvenio.setBorder(null);

        txtRg.setEditable(false);
        txtRg.setBorder(null);

        lblEndereco.setText("Endereço");

        lblCpfConsulta.setText("Informe o CPF");

        txtEndereco.setEditable(false);
        txtEndereco.setBorder(null);

        lblCelular.setText("Celular");

        btnConsultar.setBackground(new java.awt.Color(153, 153, 255));
        btnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultar.setText("Consultar");

        txtCelular.setEditable(false);
        txtCelular.setBorder(null);

        separadorVertical.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblFuma.setText("Fuma?");

        btnRadGroupFuma.add(btnRadFumaSim);
        btnRadFumaSim.setText("Sim");

        btnRadGroupFuma.add(btnRadFumaNao);
        btnRadFumaNao.setText("Não");

        lblBebe.setText("Bebe?");

        btnRadGroupBebe.add(btnRadBebeSim);
        btnRadBebeSim.setText("Sim");

        btnRadGroupBebe.add(btnRadBebeNao);
        btnRadBebeNao.setText("Não");

        lblColesterol.setText("Colesterol?");

        btnRadGroupColesterol.add(btnRadColesterolSim);
        btnRadColesterolSim.setText("Sim");

        btnRadGroupColesterol.add(btnRadColesterolNao);
        btnRadColesterolNao.setText("Não");

        lblDiabetes.setText("Diabetes?");

        btnRadGroupDiabetes.add(btnRadDiabetesSim);
        btnRadDiabetesSim.setText("Sim");

        btnRadGroupDiabetes.add(btnRadDiabetesNao);
        btnRadDiabetesNao.setText("Não");

        lblAlergias.setText("Alergias?");

        btnRadGroupAlergias.add(btnRadAlergiaSim);
        btnRadAlergiaSim.setText("Sim");

        btnRadGroupAlergias.add(btnRadAlergiaNao);
        btnRadAlergiaNao.setText("Não");

        lblProbCardiacos.setText("Problema Cardíaco?");

        btnRadGroupProbCardiaco.add(btnRadProbCardiacoSim);
        btnRadProbCardiacoSim.setText("Sim");

        btnRadGroupProbCardiaco.add(btnRadProbCardiacoNao);
        btnRadProbCardiacoNao.setText("Não");

        lblCirurgias.setText("Cirurgias?");

        btnRadGroupCirurgia.add(btnRadCirurgiaSim);
        btnRadCirurgiaSim.setText("Sim");

        btnRadGroupCirurgia.add(btnRadCirurgiaNao);
        btnRadCirurgiaNao.setText("Não");

        btnCadastrar.setBackground(new java.awt.Color(0, 153, 255));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCpfConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar))
                    .addComponent(txtNome)
                    .addComponent(txtCpf)
                    .addComponent(txtRg)
                    .addComponent(txtEndereco)
                    .addComponent(txtCelular)
                    .addComponent(txtEmail)
                    .addComponent(txtDtNasc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCpfConsulta)
                            .addComponent(lblNome)
                            .addComponent(lblCpf)
                            .addComponent(lblRg)
                            .addComponent(lblEndereco)
                            .addComponent(lblCelular)
                            .addComponent(lblEmail)
                            .addComponent(lblDtNasc)
                            .addComponent(lblConvenio))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtConvenio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separadorVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separador5)
                            .addComponent(lblProbCardiacos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separador1)
                            .addComponent(separador2)
                            .addComponent(separador3)
                            .addComponent(separador4)
                            .addComponent(separador6)
                            .addComponent(separador7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFuma)
                                    .addComponent(lblColesterol)
                                    .addComponent(lblDiabetes)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRadAlergiaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRadAlergiaNao))
                                    .addComponent(lblBebe)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRadFumaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnRadFumaNao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRadBebeSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRadBebeNao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRadColesterolSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRadColesterolNao))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRadDiabetesSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRadDiabetesNao))
                                    .addComponent(lblAlergias)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRadProbCardiacoSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRadProbCardiacoNao))
                                    .addComponent(lblCirurgias)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRadCirurgiaSim)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRadCirurgiaNao)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnCadastrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCpfConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpfConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblDtNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConvenio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtConvenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separadorVertical)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblFuma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRadFumaSim)
                                    .addComponent(btnRadFumaNao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBebe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRadBebeSim)
                                    .addComponent(btnRadBebeNao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblColesterol)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRadColesterolSim)
                                    .addComponent(btnRadColesterolNao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDiabetes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRadDiabetesSim)
                                    .addComponent(btnRadDiabetesNao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAlergias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRadAlergiaSim)
                                    .addComponent(btnRadAlergiaNao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separador5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblProbCardiacos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRadProbCardiacoSim)
                                    .addComponent(btnRadProbCardiacoNao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(separador6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCirurgias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRadCirurgiaSim)
                                    .addComponent(btnRadCirurgiaNao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(separador7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadastrar)
                                .addGap(5, 5, 5)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadDadosAdcView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadDadosAdcView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadDadosAdcView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadDadosAdcView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadDadosAdcView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JRadioButton btnRadAlergiaNao;
    private javax.swing.JRadioButton btnRadAlergiaSim;
    private javax.swing.JRadioButton btnRadBebeNao;
    private javax.swing.JRadioButton btnRadBebeSim;
    private javax.swing.JRadioButton btnRadCirurgiaNao;
    private javax.swing.JRadioButton btnRadCirurgiaSim;
    private javax.swing.JRadioButton btnRadColesterolNao;
    private javax.swing.JRadioButton btnRadColesterolSim;
    private javax.swing.JRadioButton btnRadDiabetesNao;
    private javax.swing.JRadioButton btnRadDiabetesSim;
    private javax.swing.JRadioButton btnRadFumaNao;
    private javax.swing.JRadioButton btnRadFumaSim;
    private javax.swing.ButtonGroup btnRadGroupAlergias;
    private javax.swing.ButtonGroup btnRadGroupBebe;
    private javax.swing.ButtonGroup btnRadGroupCirurgia;
    private javax.swing.ButtonGroup btnRadGroupColesterol;
    private javax.swing.ButtonGroup btnRadGroupDiabetes;
    private javax.swing.ButtonGroup btnRadGroupFuma;
    private javax.swing.ButtonGroup btnRadGroupProbCardiaco;
    private javax.swing.JRadioButton btnRadProbCardiacoNao;
    private javax.swing.JRadioButton btnRadProbCardiacoSim;
    private javax.swing.JLabel lblAlergias;
    private javax.swing.JLabel lblBebe;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCirurgias;
    private javax.swing.JLabel lblColesterol;
    private javax.swing.JLabel lblConvenio;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpfConsulta;
    private javax.swing.JLabel lblDiabetes;
    private javax.swing.JLabel lblDtNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblFuma;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProbCardiacos;
    private javax.swing.JLabel lblRg;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JSeparator separador6;
    private javax.swing.JSeparator separador7;
    private javax.swing.JSeparator separadorVertical;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtConvenio;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtCpfConsulta;
    private javax.swing.JTextField txtDtNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRg;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("icone.png"))));
    }

    public JButton getBtnCadastrar() {
        return btnCadastrar;
    }

    public void setBtnCadastrar(JButton btnCadastrar) {
        this.btnCadastrar = btnCadastrar;
    }

    public JButton getBtnConsultar() {
        return btnConsultar;
    }

    public void setBtnConsultar(JButton btnConsultar) {
        this.btnConsultar = btnConsultar;
    }

    public JRadioButton getBtnRadAlergiaNao() {
        return btnRadAlergiaNao;
    }

    public void setBtnRadAlergiaNao(JRadioButton btnRadAlergiaNao) {
        this.btnRadAlergiaNao = btnRadAlergiaNao;
    }

    public JRadioButton getBtnRadAlergiaSim() {
        return btnRadAlergiaSim;
    }

    public void setBtnRadAlergiaSim(JRadioButton btnRadAlergiaSim) {
        this.btnRadAlergiaSim = btnRadAlergiaSim;
    }

    public JRadioButton getBtnRadBebeNao() {
        return btnRadBebeNao;
    }

    public void setBtnRadBebeNao(JRadioButton btnRadBebeNao) {
        this.btnRadBebeNao = btnRadBebeNao;
    }

    public JRadioButton getBtnRadBebeSim() {
        return btnRadBebeSim;
    }

    public void setBtnRadBebeSim(JRadioButton btnRadBebeSim) {
        this.btnRadBebeSim = btnRadBebeSim;
    }

    public JRadioButton getBtnRadCirurgiaNao() {
        return btnRadCirurgiaNao;
    }

    public void setBtnRadCirurgiaNao(JRadioButton btnRadCirurgiaNao) {
        this.btnRadCirurgiaNao = btnRadCirurgiaNao;
    }

    public JRadioButton getBtnRadCirurgiaSim() {
        return btnRadCirurgiaSim;
    }

    public void setBtnRadCirurgiaSim(JRadioButton btnRadCirurgiaSim) {
        this.btnRadCirurgiaSim = btnRadCirurgiaSim;
    }

    public JRadioButton getBtnRadColesterolNao() {
        return btnRadColesterolNao;
    }

    public void setBtnRadColesterolNao(JRadioButton btnRadColesterolNao) {
        this.btnRadColesterolNao = btnRadColesterolNao;
    }

    public JRadioButton getBtnRadColesterolSim() {
        return btnRadColesterolSim;
    }

    public void setBtnRadColesterolSim(JRadioButton btnRadColesterolSim) {
        this.btnRadColesterolSim = btnRadColesterolSim;
    }

    public JRadioButton getBtnRadDiabetesNao() {
        return btnRadDiabetesNao;
    }

    public void setBtnRadDiabetesNao(JRadioButton btnRadDiabetesNao) {
        this.btnRadDiabetesNao = btnRadDiabetesNao;
    }

    public JRadioButton getBtnRadDiabetesSim() {
        return btnRadDiabetesSim;
    }

    public void setBtnRadDiabetesSim(JRadioButton btnRadDiabetesSim) {
        this.btnRadDiabetesSim = btnRadDiabetesSim;
    }

    public JRadioButton getBtnRadFumaNao() {
        return btnRadFumaNao;
    }

    public void setBtnRadFumaNao(JRadioButton btnRadFumaNao) {
        this.btnRadFumaNao = btnRadFumaNao;
    }

    public JRadioButton getBtnRadFumaSim() {
        return btnRadFumaSim;
    }

    public void setBtnRadFumaSim(JRadioButton btnRadFumaSim) {
        this.btnRadFumaSim = btnRadFumaSim;
    }

    public ButtonGroup getBtnRadGroupAlergias() {
        return btnRadGroupAlergias;
    }

    public void setBtnRadGroupAlergias(ButtonGroup btnRadGroupAlergias) {
        this.btnRadGroupAlergias = btnRadGroupAlergias;
    }

    public ButtonGroup getBtnRadGroupBebe() {
        return btnRadGroupBebe;
    }

    public void setBtnRadGroupBebe(ButtonGroup btnRadGroupBebe) {
        this.btnRadGroupBebe = btnRadGroupBebe;
    }

    public ButtonGroup getBtnRadGroupCirurgia() {
        return btnRadGroupCirurgia;
    }

    public void setBtnRadGroupCirurgia(ButtonGroup btnRadGroupCirurgia) {
        this.btnRadGroupCirurgia = btnRadGroupCirurgia;
    }

    public ButtonGroup getBtnRadGroupColesterol() {
        return btnRadGroupColesterol;
    }

    public void setBtnRadGroupColesterol(ButtonGroup btnRadGroupColesterol) {
        this.btnRadGroupColesterol = btnRadGroupColesterol;
    }

    public ButtonGroup getBtnRadGroupDiabetes() {
        return btnRadGroupDiabetes;
    }

    public void setBtnRadGroupDiabetes(ButtonGroup btnRadGroupDiabetes) {
        this.btnRadGroupDiabetes = btnRadGroupDiabetes;
    }

    public ButtonGroup getBtnRadGroupFuma() {
        return btnRadGroupFuma;
    }

    public void setBtnRadGroupFuma(ButtonGroup btnRadGroupFuma) {
        this.btnRadGroupFuma = btnRadGroupFuma;
    }

    public ButtonGroup getBtnRadGroupProbCardiaco() {
        return btnRadGroupProbCardiaco;
    }

    public void setBtnRadGroupProbCardiaco(ButtonGroup btnRadGroupProbCardiaco) {
        this.btnRadGroupProbCardiaco = btnRadGroupProbCardiaco;
    }

    public JRadioButton getBtnRadProbCardiacoNao() {
        return btnRadProbCardiacoNao;
    }

    public void setBtnRadProbCardiacoNao(JRadioButton btnRadProbCardiacoNao) {
        this.btnRadProbCardiacoNao = btnRadProbCardiacoNao;
    }

    public JRadioButton getBtnRadProbCardiacoSim() {
        return btnRadProbCardiacoSim;
    }

    public void setBtnRadProbCardiacoSim(JRadioButton btnRadProbCardiacoSim) {
        this.btnRadProbCardiacoSim = btnRadProbCardiacoSim;
    }

    public JTextField getTxtCelular() {
        return txtCelular;
    }

    public void setTxtCelular(JTextField txtCelular) {
        this.txtCelular = txtCelular;
    }

    public JTextField getTxtConvenio() {
        return txtConvenio;
    }

    public void setTxtConvenio(JTextField txtConvenio) {
        this.txtConvenio = txtConvenio;
    }

    public JTextField getTxtCpf() {
        return txtCpf;
    }

    public void setTxtCpf(JTextField txtCpf) {
        this.txtCpf = txtCpf;
    }

    public JTextField getTxtCpfConsulta() {
        return txtCpfConsulta;
    }

    public void setTxtCpfConsulta(JTextField txtCpfConsulta) {
        this.txtCpfConsulta = txtCpfConsulta;
    }

    public JTextField getTxtDtNasc() {
        return txtDtNasc;
    }

    public void setTxtDtNasc(JTextField txtDtNasc) {
        this.txtDtNasc = txtDtNasc;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getTxtEndereco() {
        return txtEndereco;
    }

    public void setTxtEndereco(JTextField txtEndereco) {
        this.txtEndereco = txtEndereco;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JTextField getTxtRg() {
        return txtRg;
    }

    public void setTxtRg(JTextField txtRg) {
        this.txtRg = txtRg;
    }
}
