/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.JButton;

/**
 *
 * @author luiz.pereira
 */
public class MedicoView extends javax.swing.JFrame {

    /**
     * Creates new form MedicoView
     */
    public MedicoView() {
        setTitle("Menu Médico | Saúde & Cia");
        setIcon();
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReceita = new javax.swing.JButton();
        pnlDadosAdc = new javax.swing.JPanel();
        btnCadDadosAdc = new javax.swing.JButton();
        btnConsDadosAdc = new javax.swing.JButton();
        btnAltDadosAdc = new javax.swing.JButton();
        btnDelDadosAdc = new javax.swing.JButton();
        pnlProntuarios = new javax.swing.JPanel();
        btnCadPront = new javax.swing.JButton();
        btnConsPront = new javax.swing.JButton();
        btnAltPront = new javax.swing.JButton();
        btnDelPront = new javax.swing.JButton();
        pnlRelatorio = new javax.swing.JPanel();
        btnAtendMes = new javax.swing.JButton();
        pnlReceitasAtestados = new javax.swing.JPanel();
        btnReceitas = new javax.swing.JButton();
        btnAtestados = new javax.swing.JButton();
        btnAtestAcomp = new javax.swing.JButton();

        btnReceita.setBackground(new java.awt.Color(102, 51, 0));
        btnReceita.setForeground(new java.awt.Color(255, 255, 255));
        btnReceita.setText("Receita");
        btnReceita.setMaximumSize(new java.awt.Dimension(80, 23));
        btnReceita.setMinimumSize(new java.awt.Dimension(80, 23));
        btnReceita.setPreferredSize(new java.awt.Dimension(80, 23));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(487, 262));

        pnlDadosAdc.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Dados Adicionais"));

        btnCadDadosAdc.setBackground(new java.awt.Color(0, 153, 255));
        btnCadDadosAdc.setForeground(new java.awt.Color(255, 255, 255));
        btnCadDadosAdc.setText("Cadastrar");

        btnConsDadosAdc.setBackground(new java.awt.Color(153, 153, 255));
        btnConsDadosAdc.setForeground(new java.awt.Color(255, 255, 255));
        btnConsDadosAdc.setText("Consultar");

        btnAltDadosAdc.setBackground(new java.awt.Color(255, 102, 102));
        btnAltDadosAdc.setForeground(new java.awt.Color(255, 255, 255));
        btnAltDadosAdc.setText("Alterar");

        btnDelDadosAdc.setBackground(new java.awt.Color(51, 204, 0));
        btnDelDadosAdc.setForeground(new java.awt.Color(255, 255, 255));
        btnDelDadosAdc.setText("Deletar");

        javax.swing.GroupLayout pnlDadosAdcLayout = new javax.swing.GroupLayout(pnlDadosAdc);
        pnlDadosAdc.setLayout(pnlDadosAdcLayout);
        pnlDadosAdcLayout.setHorizontalGroup(
            pnlDadosAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosAdcLayout.createSequentialGroup()
                .addGroup(pnlDadosAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAltDadosAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadDadosAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlDadosAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDelDadosAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsDadosAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlDadosAdcLayout.setVerticalGroup(
            pnlDadosAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosAdcLayout.createSequentialGroup()
                .addGroup(pnlDadosAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadDadosAdc)
                    .addComponent(btnConsDadosAdc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltDadosAdc)
                    .addComponent(btnDelDadosAdc)))
        );

        pnlProntuarios.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Prontuários"));

        btnCadPront.setBackground(new java.awt.Color(0, 153, 255));
        btnCadPront.setForeground(new java.awt.Color(255, 255, 255));
        btnCadPront.setText("Cadastrar");

        btnConsPront.setBackground(new java.awt.Color(153, 153, 255));
        btnConsPront.setForeground(new java.awt.Color(255, 255, 255));
        btnConsPront.setText("Consultar");

        btnAltPront.setBackground(new java.awt.Color(255, 102, 102));
        btnAltPront.setForeground(new java.awt.Color(255, 255, 255));
        btnAltPront.setText("Alterar");

        btnDelPront.setBackground(new java.awt.Color(51, 204, 0));
        btnDelPront.setForeground(new java.awt.Color(255, 255, 255));
        btnDelPront.setText("Deletar");

        javax.swing.GroupLayout pnlProntuariosLayout = new javax.swing.GroupLayout(pnlProntuarios);
        pnlProntuarios.setLayout(pnlProntuariosLayout);
        pnlProntuariosLayout.setHorizontalGroup(
            pnlProntuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProntuariosLayout.createSequentialGroup()
                .addGroup(pnlProntuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAltPront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadPront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlProntuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsPront, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btnDelPront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlProntuariosLayout.setVerticalGroup(
            pnlProntuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProntuariosLayout.createSequentialGroup()
                .addGroup(pnlProntuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadPront)
                    .addComponent(btnConsPront))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlProntuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltPront)
                    .addComponent(btnDelPront)))
        );

        pnlRelatorio.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Relatório"));

        btnAtendMes.setBackground(new java.awt.Color(0, 153, 153));
        btnAtendMes.setForeground(new java.awt.Color(255, 255, 255));
        btnAtendMes.setText("Atendimentos no mês");

        javax.swing.GroupLayout pnlRelatorioLayout = new javax.swing.GroupLayout(pnlRelatorio);
        pnlRelatorio.setLayout(pnlRelatorioLayout);
        pnlRelatorioLayout.setHorizontalGroup(
            pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAtendMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRelatorioLayout.setVerticalGroup(
            pnlRelatorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAtendMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlReceitasAtestados.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Receitas e Atestados"));

        btnReceitas.setBackground(new java.awt.Color(153, 204, 0));
        btnReceitas.setForeground(new java.awt.Color(255, 255, 255));
        btnReceitas.setText("Receitas");
        btnReceitas.setMaximumSize(new java.awt.Dimension(79, 23));
        btnReceitas.setMinimumSize(new java.awt.Dimension(79, 23));
        btnReceitas.setPreferredSize(new java.awt.Dimension(79, 23));

        btnAtestados.setBackground(new java.awt.Color(0, 102, 102));
        btnAtestados.setForeground(new java.awt.Color(255, 255, 255));
        btnAtestados.setText("Atestados");

        btnAtestAcomp.setBackground(new java.awt.Color(0, 102, 102));
        btnAtestAcomp.setForeground(new java.awt.Color(255, 255, 255));
        btnAtestAcomp.setText("Atestado de acompanhante");

        javax.swing.GroupLayout pnlReceitasAtestadosLayout = new javax.swing.GroupLayout(pnlReceitasAtestados);
        pnlReceitasAtestados.setLayout(pnlReceitasAtestadosLayout);
        pnlReceitasAtestadosLayout.setHorizontalGroup(
            pnlReceitasAtestadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReceitasAtestadosLayout.createSequentialGroup()
                .addComponent(btnReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAtestados))
            .addComponent(btnAtestAcomp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlReceitasAtestadosLayout.setVerticalGroup(
            pnlReceitasAtestadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReceitasAtestadosLayout.createSequentialGroup()
                .addGroup(pnlReceitasAtestadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReceitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtestados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAtestAcomp))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDadosAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlReceitasAtestados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlProntuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProntuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDadosAdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlReceitasAtestados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MedicoView().setVisible(true);
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("icone.png"))));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltDadosAdc;
    private javax.swing.JButton btnAltPront;
    private javax.swing.JButton btnAtendMes;
    private javax.swing.JButton btnAtestAcomp;
    private javax.swing.JButton btnAtestados;
    private javax.swing.JButton btnCadDadosAdc;
    private javax.swing.JButton btnCadPront;
    private javax.swing.JButton btnConsDadosAdc;
    private javax.swing.JButton btnConsPront;
    private javax.swing.JButton btnDelDadosAdc;
    private javax.swing.JButton btnDelPront;
    private javax.swing.JButton btnReceita;
    private javax.swing.JButton btnReceitas;
    private javax.swing.JPanel pnlDadosAdc;
    private javax.swing.JPanel pnlProntuarios;
    private javax.swing.JPanel pnlReceitasAtestados;
    private javax.swing.JPanel pnlRelatorio;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAltDadosAdc() {
        return btnAltDadosAdc;
    }

    public JButton getBtnAltPront() {
        return btnAltPront;
    }

    public JButton getBtnAtendMes() {
        return btnAtendMes;
    }

    public JButton getBtnAtestAcomp() {
        return btnAtestAcomp;
    }

    public JButton getBtnAtestados() {
        return btnAtestados;
    }

    public JButton getBtnCadDadosAdc() {
        return btnCadDadosAdc;
    }

    public JButton getBtnCadPront() {
        return btnCadPront;
    }

    public JButton getBtnConsDadosAdc() {
        return btnConsDadosAdc;
    }

    public JButton getBtnConsPront() {
        return btnConsPront;
    }

    public JButton getBtnDelDadosAdc() {
        return btnDelDadosAdc;
    }

    public JButton getBtnDelPront() {
        return btnDelPront;
    }

    public JButton getBtnReceita() {
        return btnReceita;
    }

    public JButton getBtnReceitas() {
        return btnReceitas;
    }
}
