/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Toolkit;
import javax.swing.JButton;

/**
 *
 * @author luiz.pereira
 */
public class SecretariaView extends javax.swing.JFrame {

    /**
     * Creates new form SecretariaView
     */
    public SecretariaView() {
        setTitle("Menu Secretária | Saúde & Cia");
        initComponents();
        setIcon();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPacientes = new javax.swing.JPanel();
        btnCadPac = new javax.swing.JButton();
        btnConsPac = new javax.swing.JButton();
        btnAltPac = new javax.swing.JButton();
        btnDelPac = new javax.swing.JButton();
        pnlMedicos = new javax.swing.JPanel();
        btnCadMed = new javax.swing.JButton();
        btnConsMed = new javax.swing.JButton();
        btnAltMed = new javax.swing.JButton();
        btnDelMed = new javax.swing.JButton();
        pnlConsultas = new javax.swing.JPanel();
        btnCadCon = new javax.swing.JButton();
        btnConsCon = new javax.swing.JButton();
        btnAltCon = new javax.swing.JButton();
        btnDelCon = new javax.swing.JButton();
        pnlRelatorios = new javax.swing.JPanel();
        btnConsAmanha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlPacientes.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Pacientes\n"));

        btnCadPac.setBackground(new java.awt.Color(0, 153, 255));
        btnCadPac.setForeground(new java.awt.Color(255, 255, 255));
        btnCadPac.setText("Cadastrar");

        btnConsPac.setBackground(new java.awt.Color(153, 153, 255));
        btnConsPac.setForeground(new java.awt.Color(255, 255, 255));
        btnConsPac.setText("Consultar");

        btnAltPac.setBackground(new java.awt.Color(255, 102, 102));
        btnAltPac.setForeground(new java.awt.Color(255, 255, 255));
        btnAltPac.setText("Alterar");

        btnDelPac.setBackground(new java.awt.Color(51, 204, 0));
        btnDelPac.setForeground(new java.awt.Color(255, 255, 255));
        btnDelPac.setText("Deletar");

        javax.swing.GroupLayout pnlPacientesLayout = new javax.swing.GroupLayout(pnlPacientes);
        pnlPacientes.setLayout(pnlPacientesLayout);
        pnlPacientesLayout.setHorizontalGroup(
            pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacientesLayout.createSequentialGroup()
                .addGroup(pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAltPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelPac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlPacientesLayout.setVerticalGroup(
            pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPacientesLayout.createSequentialGroup()
                .addGroup(pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadPac)
                    .addComponent(btnConsPac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltPac)
                    .addComponent(btnDelPac)))
        );

        pnlMedicos.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Médicos"));

        btnCadMed.setBackground(new java.awt.Color(0, 153, 255));
        btnCadMed.setForeground(new java.awt.Color(255, 255, 255));
        btnCadMed.setText("Cadastrar");

        btnConsMed.setBackground(new java.awt.Color(153, 153, 255));
        btnConsMed.setForeground(new java.awt.Color(255, 255, 255));
        btnConsMed.setText("Consultar");

        btnAltMed.setBackground(new java.awt.Color(255, 102, 102));
        btnAltMed.setForeground(new java.awt.Color(255, 255, 255));
        btnAltMed.setText("Alterar");

        btnDelMed.setBackground(new java.awt.Color(51, 204, 0));
        btnDelMed.setForeground(new java.awt.Color(255, 255, 255));
        btnDelMed.setText("Deletar");

        javax.swing.GroupLayout pnlMedicosLayout = new javax.swing.GroupLayout(pnlMedicos);
        pnlMedicos.setLayout(pnlMedicosLayout);
        pnlMedicosLayout.setHorizontalGroup(
            pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMedicosLayout.createSequentialGroup()
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAltMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadMed, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMedicosLayout.setVerticalGroup(
            pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicosLayout.createSequentialGroup()
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadMed)
                    .addComponent(btnConsMed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMedicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltMed)
                    .addComponent(btnDelMed)))
        );

        pnlConsultas.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Consultas"));

        btnCadCon.setBackground(new java.awt.Color(0, 153, 255));
        btnCadCon.setForeground(new java.awt.Color(255, 255, 255));
        btnCadCon.setText("Cadastrar");

        btnConsCon.setBackground(new java.awt.Color(153, 153, 255));
        btnConsCon.setForeground(new java.awt.Color(255, 255, 255));
        btnConsCon.setText("Consultar");

        btnAltCon.setBackground(new java.awt.Color(255, 102, 102));
        btnAltCon.setForeground(new java.awt.Color(255, 255, 255));
        btnAltCon.setText("Alterar");

        btnDelCon.setBackground(new java.awt.Color(51, 204, 0));
        btnDelCon.setForeground(new java.awt.Color(255, 255, 255));
        btnDelCon.setText("Deletar");

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAltCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadCon)
                    .addComponent(btnConsCon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltCon)
                    .addComponent(btnDelCon)))
        );

        pnlRelatorios.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true), "Relatório"));

        btnConsAmanha.setBackground(new java.awt.Color(153, 153, 255));
        btnConsAmanha.setForeground(new java.awt.Color(255, 255, 255));
        btnConsAmanha.setText("Consultas de Amanhã");
        btnConsAmanha.setActionCommand("");
        btnConsAmanha.setMaximumSize(new java.awt.Dimension(79, 23));
        btnConsAmanha.setMinimumSize(new java.awt.Dimension(79, 23));

        javax.swing.GroupLayout pnlRelatoriosLayout = new javax.swing.GroupLayout(pnlRelatorios);
        pnlRelatorios.setLayout(pnlRelatoriosLayout);
        pnlRelatoriosLayout.setHorizontalGroup(
            pnlRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsAmanha, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        pnlRelatoriosLayout.setVerticalGroup(
            pnlRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsAmanha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnConsAmanha.getAccessibleContext().setAccessibleName("Consultas \nde\n amanhã");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMedicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretariaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SecretariaView().setVisible(true);
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage((getClass().getResource("icone.png"))));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltCon;
    private javax.swing.JButton btnAltMed;
    private javax.swing.JButton btnAltPac;
    private javax.swing.JButton btnCadCon;
    private javax.swing.JButton btnCadMed;
    private javax.swing.JButton btnCadPac;
    private javax.swing.JButton btnConsAmanha;
    private javax.swing.JButton btnConsCon;
    private javax.swing.JButton btnConsMed;
    private javax.swing.JButton btnConsPac;
    private javax.swing.JButton btnDelCon;
    private javax.swing.JButton btnDelMed;
    private javax.swing.JButton btnDelPac;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JPanel pnlMedicos;
    private javax.swing.JPanel pnlPacientes;
    private javax.swing.JPanel pnlRelatorios;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAltCon() {
        return btnAltCon;
    }

    public JButton getBtnAltMed() {
        return btnAltMed;
    }

    public JButton getBtnAltPac() {
        return btnAltPac;
    }

    public JButton getBtnCadCon() {
        return btnCadCon;
    }

    public JButton getBtnCadMed() {
        return btnCadMed;
    }

    public JButton getBtnCadPac() {
        return btnCadPac;
    }

    public JButton getBtnConsAmanha() {
        return btnConsAmanha;
    }

    public JButton getBtnConsCon() {
        return btnConsCon;
    }

    public JButton getBtnConsMed() {
        return btnConsMed;
    }

    public JButton getBtnConsPac() {
        return btnConsPac;
    }

    public JButton getBtnDelCon() {
        return btnDelCon;
    }

    public JButton getBtnDelMed() {
        return btnDelMed;
    }

    public JButton getBtnDelPac() {
        return btnDelPac;
    }
}
